#!/bin/bash
# Root directory for ebooks
ROOT_DIR="./Ebooks"

# Declare an array of directories
DIRS=(
  "$ROOT_DIR/000_Information_Technology/001_Foundations/Computer_Science_Theory"
  "$ROOT_DIR/000_Information_Technology/001_Foundations/Algorithms_Data_Structures"
  "$ROOT_DIR/000_Information_Technology/001_Foundations/Computer_Architecture"
  "$ROOT_DIR/000_Information_Technology/001_Foundations/Mathematics_for_Computing"
  "$ROOT_DIR/000_Information_Technology/001_Foundations/Compilers_Language_Theory"
  "$ROOT_DIR/000_Information_Technology/001_Foundations/Computer_Graphics"
  "$ROOT_DIR/000_Information_Technology/001_Foundations/Human_Computer_Interaction"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Operating_Systems/Unix_Linux"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Operating_Systems/BSD"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Operating_Systems/Windows"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Operating_Systems/Theory_Design"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Databases/Relational_SQL"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Databases/NoSQL"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Databases/Database_Theory"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Computer_Networks"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Distributed_Systems"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Hardware_Embedded"
  "$ROOT_DIR/000_Information_Technology/002_Systems_Infrastructure/Storage_File_Systems"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Programming_Fundamentals"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Software_Engineering/Design_Patterns"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Software_Engineering/Testing_QA"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Software_Engineering/Debugging_Performance"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Software_Engineering/Agile_Methodologies"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Software_Engineering/Clean_Code"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Assembly"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/C"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/C++"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Rust"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Go"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Java"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/C#"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Kotlin"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Swift"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Python"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/JavaScript"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/TypeScript"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Ruby"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/PHP"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Haskell"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Scala"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Clojure"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/SQL"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/R"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/MATLAB"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/HTML_CSS"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/XML_JSON"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Languages/Markdown_LaTeX"
  "$ROOT_DIR/000_Information_Technology/003_Software_Development/Version_Control/Git"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/Frontend/React"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/Frontend/Vue"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/Frontend/Angular"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/Frontend/Next_Nuxt"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/Backend/Django_Flask"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/Backend/Express_Node"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/Backend/Rails"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/Backend/Spring_Boot"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/APIs/REST"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/APIs/GraphQL"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Web_Development/APIs/gRPC"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Mobile_Development/iOS"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Mobile_Development/Android"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Mobile_Development/Cross_Platform"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Game_Development/Engines"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Game_Development/Graphics_Physics"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Game_Development/Design_Theory"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Desktop_Applications"
  "$ROOT_DIR/000_Information_Technology/004_Application_Domains/Embedded_IoT"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/Data_Science/Statistics_Analysis"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/Data_Science/Visualization"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/Data_Science/Data_Engineering"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/Big_Data/Spark"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/Big_Data/Hadoop_Ecosystem"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/Big_Data/Streaming_Processing"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/Machine_Learning/Classical_ML"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/Machine_Learning/Deep_Learning"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/Machine_Learning/Reinforcement_Learning"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/Machine_Learning/MLOps"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/AI_Applications/Natural_Language_Processing"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/AI_Applications/Computer_Vision"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/AI_Applications/Robotics"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/AI_Applications/Generative_AI"
  "$ROOT_DIR/000_Information_Technology/005_Data_AI/AI_Ethics_Society"
  "$ROOT_DIR/000_Information_Technology/006_Security/Cryptography/Applied_Cryptography"
  "$ROOT_DIR/000_Information_Technology/006_Security/Cryptography/Cryptographic_Theory"
  "$ROOT_DIR/000_Information_Technology/006_Security/Network_Security"
  "$ROOT_DIR/000_Information_Technology/006_Security/Web_Security"
  "$ROOT_DIR/000_Information_Technology/006_Security/Mobile_Security"
  "$ROOT_DIR/000_Information_Technology/006_Security/Secure_Coding"
  "$ROOT_DIR/000_Information_Technology/006_Security/Penetration_Testing"
  "$ROOT_DIR/000_Information_Technology/006_Security/Exploit_Development"
  "$ROOT_DIR/000_Information_Technology/006_Security/Digital_Forensics"
  "$ROOT_DIR/000_Information_Technology/006_Security/Incident_Response"
  "$ROOT_DIR/000_Information_Technology/006_Security/Security_Operations"
  "$ROOT_DIR/000_Information_Technology/006_Security/OSINT_Reconnaissance"
  "$ROOT_DIR/000_Information_Technology/006_Security/Compliance_Governance"
  "$ROOT_DIR/000_Information_Technology/006_Security/Privacy_Anonymity"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/AWS"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/Azure"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/GCP"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/Multi_Cloud"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/Docker"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/Kubernetes"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/Container_Security"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/Terraform"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/Ansible"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/Pulumi_CDK"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/CI_CD"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/Monitoring_Observability"
  "$ROOT_DIR/000_Information_Technology/007_DevOps_Cloud/Site_Reliability_Engineering"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/Blockchain_Cryptocurrency/Bitcoin_Ethereum"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/Blockchain_Cryptocurrency/Smart_Contracts"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/Blockchain_Cryptocurrency/DeFi_Web3"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/Quantum_Computing/Algorithms"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/Quantum_Computing/Hardware_Physics"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/Quantum_Computing/Programming_Languages"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/High_Performance_Computing/Parallel_Programming"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/High_Performance_Computing/GPU_Computing"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/High_Performance_Computing/Scientific_Computing"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/Augmented_Virtual_Reality"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/Edge_Fog_Computing"
  "$ROOT_DIR/000_Information_Technology/008_Specialized_Computing/Bioinformatics"
  "$ROOT_DIR/000_Information_Technology/009_Professional_Technology/Career_Development"
  "$ROOT_DIR/000_Information_Technology/009_Professional_Technology/Tech_Leadership_Management"
  "$ROOT_DIR/000_Information_Technology/009_Professional_Technology/Technical_Writing_Documentation"
  "$ROOT_DIR/000_Information_Technology/009_Professional_Technology/Interview_Preparation"
  "$ROOT_DIR/000_Information_Technology/009_Professional_Technology/Technology_Business"
  "$ROOT_DIR/000_Information_Technology/009_Professional_Technology/Ethics_Society"
  "$ROOT_DIR/000_Information_Technology/009_Professional_Technology/History_of_Computing"
  "$ROOT_DIR/000_Information_Technology/009_Professional_Technology/Open_Source_Communities"
  "$ROOT_DIR/000_Information_Technology/009_Professional_Technology/Knowledge_Management"
  "$ROOT_DIR/100_Philosophy_Psychology/100_Philosophy_General"
  "$ROOT_DIR/100_Philosophy_Psychology/110_Metaphysics"
  "$ROOT_DIR/100_Philosophy_Psychology/120_Epistemology"
  "$ROOT_DIR/100_Philosophy_Psychology/130_Parapsychology_Occultism"
  "$ROOT_DIR/100_Philosophy_Psychology/140_Philosophical_Schools"
  "$ROOT_DIR/100_Philosophy_Psychology/150_Psychology"
  "$ROOT_DIR/100_Philosophy_Psychology/160_Logic"
  "$ROOT_DIR/100_Philosophy_Psychology/170_Ethics"
  "$ROOT_DIR/100_Philosophy_Psychology/180_Ancient_Philosophy"
  "$ROOT_DIR/100_Philosophy_Psychology/190_Modern_Philosophy"
  "$ROOT_DIR/200_Religion/200_Religion_General"
  "$ROOT_DIR/200_Religion/210_Philosophy_of_Religion"
  "$ROOT_DIR/200_Religion/230_Christianity/Bible"
  "$ROOT_DIR/200_Religion/230_Christianity/Theology"
  "$ROOT_DIR/200_Religion/230_Christianity/History"
  "$ROOT_DIR/200_Religion/230_Christianity/Denominations/Catholicism"
  "$ROOT_DIR/200_Religion/230_Christianity/Denominations/Eastern_Orthodox"
  "$ROOT_DIR/200_Religion/230_Christianity/Denominations/Lutheranism"
  "$ROOT_DIR/200_Religion/230_Christianity/Denominations/Protestantism"
  "$ROOT_DIR/200_Religion/230_Christianity/Denominations/Reformed"
  "$ROOT_DIR/200_Religion/292_Greek_Roman_Religion"
  "$ROOT_DIR/200_Religion/293_Germanic_Religion"
  "$ROOT_DIR/200_Religion/294_Buddhism"
  "$ROOT_DIR/200_Religion/294_Zen"
  "$ROOT_DIR/200_Religion/294_Meditation"
  "$ROOT_DIR/200_Religion/295_Hinduism"
  "$ROOT_DIR/200_Religion/296_Judaism"
  "$ROOT_DIR/200_Religion/297_Islam"
  "$ROOT_DIR/200_Religion/298_Sikhism"
  "$ROOT_DIR/200_Religion/299_Shintoism"
  "$ROOT_DIR/200_Religion/299_Taoism"
  "$ROOT_DIR/200_Religion/299_Confucianism"
  "$ROOT_DIR/200_Religion/299_Native_American_Religions"
  "$ROOT_DIR/200_Religion/299_African_Traditional_Religions"
  "$ROOT_DIR/200_Religion/299_Religious_Syncretism"
  "$ROOT_DIR/200_Religion/299_Afro_Brazilian_Religions"
  "$ROOT_DIR/200_Religion/299_Norse_Mythology"
  "$ROOT_DIR/200_Religion/299_Paganism_Wicca"
  # Social Sciences: Human behavior, society, and social institutions
  "$ROOT_DIR/300_Social_Sciences/301_Anthropology"
  "$ROOT_DIR/300_Social_Sciences/301_Sociology" # Study of society and human culture
  "$ROOT_DIR/300_Social_Sciences/302_Social_Interaction" # Communication, social media, interpersonal relations
  "$ROOT_DIR/300_Social_Sciences/303_Social_Processes" # Social change, social planning, social movements
  "$ROOT_DIR/300_Social_Sciences/304_Factors_affecting_behavior" # Environmental and demographic influences
  "$ROOT_DIR/300_Social_Sciences/305_Social_Groups" # Age groups, gender studies, social classes
  "$ROOT_DIR/300_Social_Sciences/306_Culture_Institutions" # Marriage, family, cultural studies
  "$ROOT_DIR/300_Social_Sciences/307_Communities" # Rural, urban, and suburban communities
  "$ROOT_DIR/300_Social_Sciences/308_Groups_of_People" # Racial, ethnic, and national groups
  "$ROOT_DIR/300_Social_Sciences/309_Social_Situations" # Social problems and welfare
  "$ROOT_DIR/300_Social_Sciences/310_Statistics" # Social statistics and demographic data
  # Politics and Government: Political theory, systems, and processes
  # 320: Politics, Government, and Ideology
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/Political_Theory_Philosophy"   # For classics like Plato, Locke, Machiavelli, Rawls
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/Government_Systems"            # Democracy, Monarchy, Republics, Constitutions
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/The_Political_Process"         # Elections, Activism, Political Parties
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/International_Relations"       # Diplomacy, Foreign Policy, Geopolitics
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/Political_Parties"             # Party systems and organization
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/Political_Situations"          # Contemporary political issues
  # A home for all major political and economic ideologies
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/Ideologies_and_Movements/Anarchism"
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/Ideologies_and_Movements/Conservatism"
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/Ideologies_and_Movements/Fascism"
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/Ideologies_and_Movements/Liberalism"
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/Ideologies_and_Movements/Libertarianism"
  "$ROOT_DIR/300_Social_Sciences/320_Politics_Government/Ideologies_and_Movements/Socialism_Communism"
  # 330: Economics
  "$ROOT_DIR/300_Social_Sciences/330_Economics/Economic_Philosophy" # Adam Smith, Keynes, Marx (as an economist)
  "$ROOT_DIR/300_Social_Sciences/330_Economics/Schools_of_Thought/Austrian_Economics"
  "$ROOT_DIR/300_Social_Sciences/330_Economics/Schools_of_Thought/Keynesian_Economics"
  "$ROOT_DIR/300_Social_Sciences/330_Economics/Schools_of_Thought/Monetarism"
  "$ROOT_DIR/300_Social_Sciences/330_Economics/Macroeconomics"
  "$ROOT_DIR/300_Social_Sciences/330_Economics/Microeconomics"
  "$ROOT_DIR/300_Social_Sciences/330_Economics/Personal_Finance"
  "$ROOT_DIR/300_Social_Sciences/330_Economics/Labor_Economics"
  "$ROOT_DIR/300_Social_Sciences/330_Economics/International_Economics"

  "$ROOT_DIR/300_Social_Sciences/340_Law"
  "$ROOT_DIR/300_Social_Sciences/340_Law/International_Law"
  "$ROOT_DIR/300_Social_Sciences/340_Law/Constitutional_Law"
  "$ROOT_DIR/300_Social_Sciences/340_Law/Business_Law"
  "$ROOT_DIR/300_Social_Sciences/340_Law/Criminal_Law"
  "$ROOT_DIR/300_Social_Sciences/350_Public_Administration/Local_Government"
  "$ROOT_DIR/300_Social_Sciences/350_Public_Administration/Federal_Government"
  "$ROOT_DIR/300_Social_Sciences/350_Public_Administration/Military_Science/Army_Manuals" # ?
  "$ROOT_DIR/300_Social_Sciences/350_Public_Administration/Military_Science/Weapons_Training"
  "$ROOT_DIR/300_Social_Sciences/350_Public_Administration/Military_Science/Intelligence_Operations"
  "$ROOT_DIR/300_Social_Sciences/350_Public_Administration/Military_Science/Field_Tactics"
  "$ROOT_DIR/300_Social_Sciences/360_Social_Problems_and_Services"
  "$ROOT_DIR/300_Social_Sciences/370_Education"
  "$ROOT_DIR/300_Social_Sciences/380_Commerce_Communication"
  "$ROOT_DIR/300_Social_Sciences/390_Customs_Traditions"
  "$ROOT_DIR/300_Social_Sciences/390_Customs_Traditions/391.1_Scottish_Tartans" # ?
  "$ROOT_DIR/300_Social_Sciences/390_Customs_Traditions/391_Fashion/"
  "$ROOT_DIR/400_Language"
  "$ROOT_DIR/400_Language/410_Linguistics/Writing_Systems"
  "$ROOT_DIR/400_Language/410_Linguistics/Etymology"
  "$ROOT_DIR/400_Language/410_Linguistics/Dictionaries"
  "$ROOT_DIR/400_Language/410_Linguistics/Phonology"
  "$ROOT_DIR/400_Language/410_Linguistics/Grammar"
  "$ROOT_DIR/400_Language/410_Linguistics/Semantics"
  "$ROOT_DIR/400_Language/410_Linguistics/Dialectology"
  "$ROOT_DIR/400_Language/410_Linguistics/Standard_Usage"
  "$ROOT_DIR/400_Language/410_Linguistics/Sign_Languages"
  "$ROOT_DIR/400_Language/410_Linguistics/Syntax"
  "$ROOT_DIR/400_Language/410_Linguistics/Morphology"
  "$ROOT_DIR/400_Language/410_Linguistics/Sociolinguistics"
  "$ROOT_DIR/400_Language/420_English_Language/Writing_System"
  "$ROOT_DIR/400_Language/420_English_Language/Etymology"
  "$ROOT_DIR/400_Language/420_English_Language/Dictionaries"
  "$ROOT_DIR/400_Language/420_English_Language/Grammar"
  "$ROOT_DIR/400_Language/420_English_Language/Dialects"
  "$ROOT_DIR/400_Language/420_English_Language/Usage"
  "$ROOT_DIR/400_Language/430_German_Language/Writing_System"
  "$ROOT_DIR/400_Language/430_German_Language/Etymology"
  "$ROOT_DIR/400_Language/430_German_Language/Dictionaries"
  "$ROOT_DIR/400_Language/430_German_Language/Grammar"
  "$ROOT_DIR/400_Language/430_German_Language/Dialects"
  "$ROOT_DIR/400_Language/430_German_Language/Usage"
  "$ROOT_DIR/400_Language/431_Dutch_Language"
  "$ROOT_DIR/400_Language/432_Norwegian_Language"
  "$ROOT_DIR/400_Language/433_Swedish_Language"
  "$ROOT_DIR/400_Language/434_Danish_Language"
  "$ROOT_DIR/400_Language/440_French_Language"
  "$ROOT_DIR/400_Language/450_Italian_Language"
  "$ROOT_DIR/400_Language/460_Spanish_Language"
  "$ROOT_DIR/400_Language/460.9_Galego_Language"
  "$ROOT_DIR/400_Language/469_Portuguese_Language/Portuguese"
  "$ROOT_DIR/400_Language/469_Portuguese_Language/Brazilian_Portuguese"
  "$ROOT_DIR/400_Language/470_Latin_Language"
  "$ROOT_DIR/400_Language/480_Greek_Language"
  "$ROOT_DIR/400_Language/491_Russian_Language"
  "$ROOT_DIR/400_Language/492_Arabic_Language/Writing_System"
  "$ROOT_DIR/400_Language/492_Arabic_Language/Dictionaries"
  "$ROOT_DIR/400_Language/492_Arabic_Language/Grammar"
  "$ROOT_DIR/400_Language/492_Arabic_Language/Dialects/Iraqi_Arabic"
  "$ROOT_DIR/400_Language/492_Arabic_Language/Dialects/Gulf_Arabic"
  "$ROOT_DIR/400_Language/492_Arabic_Language/Dialects/Levantine_Arabic"
  "$ROOT_DIR/400_Language/492_Arabic_Language/Dialects/Egyptian_Arabic"
  "$ROOT_DIR/400_Language/492_Arabic_Language/Dialects/Yemeni_Arabic"
  "$ROOT_DIR/400_Language/493_Hebrew_Language"
  "$ROOT_DIR/400_Language/494_Turkish_Language"
  "$ROOT_DIR/400_Language/495_Chinese_Language"
  "$ROOT_DIR/400_Language/495.1_Japanese_Language"
  "$ROOT_DIR/400_Language/495.2_Manchu_Language"
  "$ROOT_DIR/400_Language/495.7_Korean_Language"
  "$ROOT_DIR/400_Language/496_Swahili_Language"
  "$ROOT_DIR/400_Language/497_Hindi_Language"
  "$ROOT_DIR/400_Language/497.1_Sanskrit_Language"
  "$ROOT_DIR/400_Language/497.2_Tibetan_Language"
  "$ROOT_DIR/400_Language/497.3_Pali_Language"
  "$ROOT_DIR/400_Language/497.8_Persian_Language"
  "$ROOT_DIR/400_Language/498_Thai_Language"
  "$ROOT_DIR/400_Language/498.1_Vietnamese_Language"
  "$ROOT_DIR/400_Language/498.2_Indonesian_Language"
  "$ROOT_DIR/400_Language/499.1_Romanian_Language"
  "$ROOT_DIR/400_Language/499.2_Hungarian_Language"
  "$ROOT_DIR/400_Language/499.3_Finnish_Language"
  "$ROOT_DIR/400_Language/499.4_Hawaiian_Language"
  "$ROOT_DIR/400_Language/499.9_Constructed_Languages/Esperanto"
  "$ROOT_DIR/400_Language/499.9_Constructed_Languages/Toki_Pona"
  "$ROOT_DIR/400_Language/499.9_Constructed_Languages/Tolkien"
  "$ROOT_DIR/400_Language/499.9_Other_Languages"
  "$ROOT_DIR/500_Science/500_Natural_Sciences_General"
  "$ROOT_DIR/500_Science/510_Mathematics/General_Principles"
  "$ROOT_DIR/500_Science/510_Mathematics/Number_Theory"
  "$ROOT_DIR/500_Science/510_Mathematics/Calculus"
  "$ROOT_DIR/500_Science/510_Mathematics/Trigonometry"
  "$ROOT_DIR/500_Science/510_Mathematics/Linear_Algebra"
  "$ROOT_DIR/500_Science/510_Mathematics/Algebra"
  "$ROOT_DIR/500_Science/510_Mathematics/Arithmetic"
  "$ROOT_DIR/500_Science/510_Mathematics/Topology"
  "$ROOT_DIR/500_Science/510_Mathematics/Analysis"
  "$ROOT_DIR/500_Science/510_Mathematics/Geometry"
  "$ROOT_DIR/500_Science/510_Mathematics/Numerical_Analysis"
  "$ROOT_DIR/500_Science/510_Mathematics/Probabilities_Statistics"
  "$ROOT_DIR/500_Science/520_Astronomy"
  "$ROOT_DIR/500_Science/530_Physics"
  "$ROOT_DIR/500_Science/540_Chemistry"
  "$ROOT_DIR/500_Science/550_Earth_Sciences"
  "$ROOT_DIR/500_Science/560_Paleontology"
  "$ROOT_DIR/500_Science/570_Biology"
  "$ROOT_DIR/500_Science/580_Botany"
  "$ROOT_DIR/500_Science/590_Zoology"
  "$ROOT_DIR/600_Technology/600_Technology_General"
  "$ROOT_DIR/600_Technology/610_Medicine_Health/First_Aid"
  "$ROOT_DIR/600_Technology/610_Medicine_Health/Nutrition"
  "$ROOT_DIR/600_Technology/620_Engineering"
  "$ROOT_DIR/600_Technology/621_Electronics_Engineering/Raspberry_Pi"
  "$ROOT_DIR/600_Technology/621_Electronics_Engineering/Arduino"
  "$ROOT_DIR/600_Technology/621_Electronics_Engineering/Home_Electronics"
  "$ROOT_DIR/600_Technology/621_Electronics_Engineering/Radio_Engineering/Ham_Radio" # ?
  "$ROOT_DIR/600_Technology/630_Agriculture/Sustainable_Agriculture"
  "$ROOT_DIR/600_Technology/630_Agriculture/Gardening_Home_Growing"
  "$ROOT_DIR/600_Technology/630_Agriculture/Animal_Husbandry"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/641_Food_and_Drink/641.2_Beverages/Beer"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/641_Food_and_Drink/641.2_Beverages/Wine"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/641_Food_and_Drink/641.2_Beverages/Liquor"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/641_Food_and_Drink/641.5_Cooking_Recipes/Italian_Cooking"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/641_Food_and_Drink/641.5_Cooking_Recipes/French_Cooking"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/641_Food_and_Drink/641.5_Cooking_Recipes/Asian_Cooking"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/641_Food_and_Drink/641.5_Cooking_Recipes/Mexican_Cooking"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/641_Food_and_Drink/641.5_Cooking_Recipes/American_Cooking"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/641_Food_and_Drink/641.87_Brewing_Distilling"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/641_Food_and_Drink/641.3_Tobacco"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/642_Meals_Table_Service" # Entertaining, formal dining, etiquette
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/643_Housing_Household_Equipment" # Home maintenance, appliances
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/645_Household_Furnishings/Home_DIY" # General home improvement projects
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/646_Sewing_Clothing/Knitting"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/646_Sewing_Clothing/Crochet"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/646_Sewing_Clothing/Quilting"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/646_Sewing_Clothing/Embroidery"
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/648_Housekeeping" # Cleaning, organizing, home management
  "$ROOT_DIR/600_Technology/640_Home_Economics_Cooking/649_Child_Rearing"
  "$ROOT_DIR/600_Technology/650_Management/651_Office_Services" # Administrative procedures, office organization
  "$ROOT_DIR/600_Technology/650_Management/652_Processes_of_Communication" # Business writing, presentations
  "$ROOT_DIR/600_Technology/650_Management/653_Shorthand"
  "$ROOT_DIR/600_Technology/650_Management/657_Accounting"
  "$ROOT_DIR/600_Technology/650_Management/658_General_Management" # GTD will go here
  "$ROOT_DIR/600_Technology/650_Management/659_Advertising_Public_Relations"
  "$ROOT_DIR/600_Technology/660_Chemical_Engineering"
  # Manufacturing: Small-scale production and artisan/maker skills
  "$ROOT_DIR/600_Technology/680_Manufacturing/681_Precision_Instruments" # Clockmaking, scientific instruments
  "$ROOT_DIR/600_Technology/680_Manufacturing/682_Small_Forge_Work" # Blacksmithing, metalworking
  "$ROOT_DIR/600_Technology/680_Manufacturing/683_Hardware" # Lock-making, small metal goods
  "$ROOT_DIR/600_Technology/680_Manufacturing/684_Furnishings" # Furniture making, woodworking
  "$ROOT_DIR/600_Technology/680_Manufacturing/685_Leather_Goods" # Leather crafting (diff from 646: commercial vs. home production)
  "$ROOT_DIR/600_Technology/680_Manufacturing/686_Printing_Publishing" # Print production, book binding
  "$ROOT_DIR/600_Technology/680_Manufacturing/687_Clothing" # Garment manufacturing (diff from 646: industrial vs. home sewing)
  "$ROOT_DIR/600_Technology/690_Building_Construction"
  "$ROOT_DIR/700_Arts_Design/700_The_Arts_General"
  "$ROOT_DIR/700_Arts_Design/710_Civic_Landscape_Art"
  "$ROOT_DIR/700_Arts_Design/720_Architecture"
  "$ROOT_DIR/700_Arts_Design/730_Sculpture"
  "$ROOT_DIR/700_Arts_Design/740_Design_Graphic_Arts"
  "$ROOT_DIR/700_Arts_Design/750_Painting"
  "$ROOT_DIR/700_Arts_Design/760_Graphic_Arts"
  "$ROOT_DIR/700_Arts_Design/770_Photography"
  "$ROOT_DIR/790_Sports_Games/796.32_Football"
  "$ROOT_DIR/790_Sports_Games/796.54_Wilderness_Survival" # ?
  "$ROOT_DIR/790_Sports_Games/794_Chess"
  "$ROOT_DIR/790_Sports_Games/799.1_Archery"
  "$ROOT_DIR/790_Sports_Games/794.4_Go"
  "$ROOT_DIR/790_Sports_Games/796.6_Cycling"
  "$ROOT_DIR/790_Sports_Games/613.7_Yoga"
  "$ROOT_DIR/790_Sports_Games/796.33_American_Football"
  "$ROOT_DIR/790_Sports_Games/796.334_Soccer"
  "$ROOT_DIR/790_Sports_Games/796.357_Baseball"
  "$ROOT_DIR/790_Sports_Games/796.8_Combat_Sports"
  "$ROOT_DIR/790_Sports_Games/796.962_Hockey"
  "$ROOT_DIR/780_Music/781_Music_Theory"
  "$ROOT_DIR/780_Music/780.9_Music_History"
  "$ROOT_DIR/780_Music/782_Vocal_Music"
  "$ROOT_DIR/780_Music/784_Instruments_Instrumental_Ensembles"
  "$ROOT_DIR/780_Music/785_Ensembles_Chamber_Music"
  # Music instruction, for specific instruments
  "$ROOT_DIR/780_Music/786_Keyboard_Instruments/Piano/Classical_Piano"
  "$ROOT_DIR/780_Music/786_Keyboard_Instruments/Piano/Jazz_Piano"
  "$ROOT_DIR/780_Music/786_Keyboard_Instruments/Piano/Blues_Piano"
  "$ROOT_DIR/780_Music/786_Keyboard_Instruments/Piano/Ragtime_Piano"
  "$ROOT_DIR/780_Music/786_Keyboard_Instruments/Piano/Popular_Piano"
  "$ROOT_DIR/780_Music/786_Keyboard_Instruments/Piano/Gospel_Piano"
  "$ROOT_DIR/780_Music/786_Keyboard_Instruments/Organ"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Guitar/Classical_Guitar"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Guitar/Jazz_Guitar"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Guitar/Blues_Guitar"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Guitar/Brazilian_Guitar"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Guitar/Bossa_Nova_Guitar"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Guitar/Flamenco_Guitar"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Guitar/Folk_Guitar"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Guitar/Rock_Guitar"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Guitar/Guitar_Construction"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Guitar/Guitar_Repair_Maintenance"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Bass"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Bouzouki"
  "$ROOT_DIR/780_Music/787_Stringed_Instruments/Plucked_Instruments"
  "$ROOT_DIR/780_Music/788_Wind_Instruments/Saxophone"
  "$ROOT_DIR/780_Music/788_Wind_Instruments/Flute"
  "$ROOT_DIR/780_Music/788_Wind_Instruments/Tin_Whistle"
  "$ROOT_DIR/780_Music/788_Wind_Instruments/Bagpipes"
  "$ROOT_DIR/780_Music/788_Wind_Instruments/Trumpet"
  "$ROOT_DIR/780_Music/786.9_Percussion"
  # Music instruction, not for specific instruments
  "$ROOT_DIR/780_Music/789_Traditions_Genres/Jazz_Instruction"
  "$ROOT_DIR/780_Music/789_Traditions_Genres/Blues_Instruction"
  "$ROOT_DIR/780_Music/789_Traditions_Genres/Brazilian_Music_Instruction"
  "$ROOT_DIR/780_Music/789_Traditions_Genres/Bossa_Nova_Instruction"
  "$ROOT_DIR/780_Music/789_Traditions_Genres/World_Music_Instruction"
  "$ROOT_DIR/780_Music/789_Traditions_Genres/Celtic_Music_Instruction"
  "$ROOT_DIR/780_Music/789_Sheet_Music/Artists_go_here"
  "$ROOT_DIR/780_Music/789_Sheet_Music/Bach"
  "$ROOT_DIR/780_Music/789_Sheet_Music/Chopin"
  "$ROOT_DIR/780_Music/789_Sheet_Music/Antonio_Carlos_Jobim"
  "$ROOT_DIR/780_Music/789_Sheet_Music/John_Coltrane"
  "$ROOT_DIR/780_Music/789_Sheet_Music/Miles_Davis"
  # Literature: Organized by original language of literary composition
  "$ROOT_DIR/800_Literature/810_English_Literature"
  "$ROOT_DIR/800_Literature/830_German_Literature"
  "$ROOT_DIR/800_Literature/840_French_Literature"
  "$ROOT_DIR/800_Literature/850_Italian_Literature"
  "$ROOT_DIR/800_Literature/860_Spanish_Literature"
  "$ROOT_DIR/800_Literature/869_Portuguese_Literature"
  "$ROOT_DIR/800_Literature/870_Latin_Literature"
  "$ROOT_DIR/800_Literature/880_Classical_Greek_Lit"
  "$ROOT_DIR/800_Literature/892_Arabic_Literature"
  "$ROOT_DIR/800_Literature/895.1_Chinese_Literature"
  "$ROOT_DIR/800_Literature/895.6_Japanese_Literature"
  "$ROOT_DIR/800_Literature/895.6_Japanese_Literature/Manga"
  "$ROOT_DIR/800_Literature/891_Russian_Literature"
  "$ROOT_DIR/800_Literature/897_African_Literature"
  "$ROOT_DIR/800_Literature/899_Canadian_Literature"
  "$ROOT_DIR/800_Literature/890_Other_Literatures"
  # Children's Literature: Organized separately from adult literature
  "$ROOT_DIR/999_Childrens_Literature/Picture_Books"
  "$ROOT_DIR/999_Childrens_Literature/Early_Readers"
  "$ROOT_DIR/999_Childrens_Literature/Middle_Grade"
  "$ROOT_DIR/999_Childrens_Literature/Young_Adult"
  "$ROOT_DIR/999_Childrens_Literature/Educational"
  # Biography: Do I want these here, or put the person in the category most relevant to them?
  "$ROOT_DIR/900_History/920_Biography/"
  "$ROOT_DIR/900_History/930_Ancient_History"
  "$ROOT_DIR/900_History/940_Europe/England"
  "$ROOT_DIR/900_History/940_Europe/Ireland"
  "$ROOT_DIR/900_History/940_Europe/Scotland"
  "$ROOT_DIR/900_History/940_Europe/Scandinavia"
  "$ROOT_DIR/900_History/940_Europe/Finland"
  "$ROOT_DIR/900_History/940_Europe/Germany"
  "$ROOT_DIR/900_History/940_Europe/France"
  "$ROOT_DIR/900_History/940_Europe/Italy"
  "$ROOT_DIR/900_History/940_Europe/Spain"
  "$ROOT_DIR/900_History/940_Europe/Portugal"
  "$ROOT_DIR/900_History/940_Europe/Romania"
  "$ROOT_DIR/900_History/950_Asia/China"
  "$ROOT_DIR/900_History/950_Asia/Japan"
  "$ROOT_DIR/900_History/950_Asia/South_Asia_India"
  "$ROOT_DIR/900_History/950_Asia/Iran"
  "$ROOT_DIR/900_History/950_Asia/Middle_East/Israel"
  "$ROOT_DIR/900_History/950_Asia/Middle_East/Iraq"
  "$ROOT_DIR/900_History/950_Asia/Middle_East/Yemen"
  "$ROOT_DIR/900_History/950_Asia/Southeast_Asia"
  "$ROOT_DIR/900_History/960_Africa"
  "$ROOT_DIR/900_History/970_North_America/Canada"
  "$ROOT_DIR/900_History/970_North_America/Cuba"
  "$ROOT_DIR/900_History/970_North_America/Mexico"
  "$ROOT_DIR/900_History/970_North_America/United_States"
  "$ROOT_DIR/900_History/970_North_America/Cascadia"
  "$ROOT_DIR/900_History/980_South_America/Brazil"
  "$ROOT_DIR/900_History/980_South_America/Argentina"
  "$ROOT_DIR/900_History/990_Oceania/Australia"
  "$ROOT_DIR/900_History/990_Oceania/New_Zealand"
  "$ROOT_DIR/910_Geography_Travel/910_Geography"
  "$ROOT_DIR/910_Geography_Travel/914_Travel_Europe/Scotland"
  "$ROOT_DIR/910_Geography_Travel/914_Travel_Europe/England"
  "$ROOT_DIR/910_Geography_Travel/914_Travel_Europe/France"
  "$ROOT_DIR/910_Geography_Travel/914_Travel_Europe/Italy"
  "$ROOT_DIR/910_Geography_Travel/914_Travel_Europe/Spain_Portugal"
  "$ROOT_DIR/910_Geography_Travel/914_Travel_Europe/Germany"
  "$ROOT_DIR/910_Geography_Travel/914_Travel_Europe/Scandinavia"
  "$ROOT_DIR/910_Geography_Travel/914_Travel_Europe/Other_Europe"
  "$ROOT_DIR/910_Geography_Travel/915_Travel_Asia/China"
  "$ROOT_DIR/910_Geography_Travel/915_Travel_Asia/Japan"
  "$ROOT_DIR/910_Geography_Travel/915_Travel_Asia/India"
  "$ROOT_DIR/910_Geography_Travel/915_Travel_Asia/Middle_East"
  "$ROOT_DIR/910_Geography_Travel/915_Travel_Asia/Southeast_Asia"
  "$ROOT_DIR/910_Geography_Travel/916_Travel_Africa"
  "$ROOT_DIR/910_Geography_Travel/917_Travel_North_America/Canada"
  "$ROOT_DIR/910_Geography_Travel/917_Travel_North_America/United_States"
  "$ROOT_DIR/910_Geography_Travel/917_Travel_North_America/Mexico"
  "$ROOT_DIR/910_Geography_Travel/917_Travel_North_America/Central_America"
  "$ROOT_DIR/910_Geography_Travel/917_Travel_North_America/Caribbean"
  "$ROOT_DIR/910_Geography_Travel/918_Travel_South_America/Brazil"
  "$ROOT_DIR/910_Geography_Travel/918_Travel_South_America/Argentina"
  "$ROOT_DIR/910_Geography_Travel/919_Travel_Oceania/Australia"
  "$ROOT_DIR/910_Geography_Travel/919_Travel_Oceania/New_Zealand"
  # Unclassified directory for books that don't fit existing structure
  "$ROOT_DIR/_Unclassified"
)

# Create each directory
for dir in "${DIRS[@]}"; do
  mkdir -p "$dir"
done

echo "✅ Dewey-based ebook library structure created at: $ROOT_DIR"
echo ""
echo "📝 Usage notes:"
echo "- Information Technology (000s): Computer science, programming, AI, and knowledge systems"
echo "- Social Sciences (300s): Note distinction between political ideologies (320s) and economic systems (330s)"
echo "- Language (400s): Organized by language families; includes both study materials and reference works"
echo "- Science (500s): Pure sciences; applied sciences go in 600s Technology"
echo "- Technology (600s): Applied sciences, including medicine, engineering, manufacturing, and domestic arts"
echo "- Arts (700s): Fine arts, recreation, sports; music organized by instrument and genre"
echo "- Literature (800s): Organized by original language of composition, not geography"
echo "- History (900s): Geography and history by region; biography goes in 920"
echo "- Electronics hardware: Raspberry Pi/Arduino in 621 (engineering), not 004 (computer science)"
echo "- Statistics: Social statistics (310) vs. mathematical statistics (519) serve different purposes"
echo "- Cross-references: Some topics could fit multiple locations - use most specific classification"


# Also, we could make a simple LLM program to be a librarian for the existing book locations (or add this ability to our program)
# where you can just ask a simple question, like the location of a book, and the LLM can tell you.
# Or a (maybe RAG?) LLM program where you can ask where a book should go?

# Would there be an appropriate single location for tobacco: growing, smoking, history, cigars, pipes?

# Any vague categories (e.g., 690) could use a comment on the line above them to explain, define, maybe give examples.

# After structure is finalized, improve usage notes.
